# Site settings
author: John Beltrez
title: John's Flatiron Blog
header-img: img/home-bg.png
email: beltrezjohn@gmail.com
copyright_name: John Beltrez
description: > # this means to ignore newlines until "baseurl:"
  Collection of 7 entries 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Jbeltrez

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
